### PR TITLE
replace dictionary comprehension with dict function

### PR DESCRIPTION
**Pull request by anxdpanic**
- Python 2.6 compat.

Tested briefly w/ Kodi 16 on Android

### CODE REVIEW

**Comment by anxdpanic** [comment]
Just seen #5, not sure you're interested in the fix. Was just fixing the issue I ran into trying https://github.com/anxdpanic/plugin.video.composite_for_plex on minimum supported python version in Jarvis.
Gotham+ is likely to have a lot of python 2.6 devices, and it is a relatively minor change so hopefully it can be included. I haven't ran into any other 2.6 specific issues.

**Comment by romanvm** [comment]
@anxdpanic  Thanks for your contribution. Have you actually tested it with Python 2.6?

**Comment by anxdpanic** [comment]
Briefly, about 20 minutes. 
The add-on mentioned above wouldn't work at all without this change, and everything seems to be working as expected with this change.

**Comment by romanvm** [comment]
OK, thanks. Then I'm merging it.

**Pull request merged**
